GET http://localhost:3000/health

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "test@example.com"
}

###

POST http://localhost:3000/list
Content-Type: application/json

{
  "userId": 1,
  "item": "milk"
}

###

GET http://localhost:3000/inventory/milk